preprocessing_steps:
  drop_instance_weight: true
  clean_strings: true
  replace_missing: true
  drop_high_na_columns: true
  drop_duplicates: true
  convert_to_category: true
  remove_correlated: true
  group_rare_categories: true
  impute_missing: false
  one_hot_encode: false
  scaling: false

col_names:
  - age
  - class_of_worker
  - detailed_industry_recode
  - detailed_occupation_recode
  - education
  - wage_per_hour
  - enroll_in_edu_last_wk
  - marital_stat
  - major_industry_code
  - major_occupation_code
  - race
  - hispanic_origin
  - sex
  - member_of_labor_union
  - reason_for_unemployment
  - full_or_part_time_stat
  - capital_gains
  - capital_losses
  - dividends_from_stocks
  - tax_filer_stat
  - region_prev_residence
  - state_prev_residence
  - household_family_stat
  - household_summary
  - instance_weight
  - msa_change_code
  - reg_change_code
  - move_within_reg
  - live_in_this_house_1_year_ago
  - prev_residence_sunbelt
  - num_persons_worked_for_employer
  - family_members_under_18
  - country_birth_father
  - country_birth_mother
  - country_birth_self
  - citizenship
  - own_business_or_self_employed
  - veterans_admin_questionnaire
  - veterans_benefits
  - weeks_worked_in_year
  - year
  - income

missing_values:
  - "?"
  - "Not in universe"
  - "Not identifiable"
  - "NA"
  - "Do not know"

cat_cols:
  - detailed_industry_recode
  - detailed_occupation_recode
  - own_business_or_self_employed
  - veterans_benefits
  - year

columns_to_remove:
  - "reg_change_code"
  - "msa_change_code"
  - "move_within_reg"
  - "detailed_industry_recode"
  - "detailed_occupation_recode"
  - "household_family_stat"